#!/usr/bin/env python2
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
"""

def evenfibsum():
    sum = 0
    a = 0
    b = 1
    c = 0
    while ( c < 4000000 ):
        if (c%2 == 0):
            sum += c
        c = a+b
        a=b
        b=c
    return sum

print "Answer: %d" % evenfibsum()



